//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JohnMoore.AmpacheNet
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_media_next = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_media_next_invert = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_media_pause = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_media_play = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_media_previous = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_media_previous_invert = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_shuffle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_shuffle_invert = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_thumbnail = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int stat_notify_musicplayer = 2130837514;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060019
			public const int albums = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int artists = 2131099672;
			
			// aapt resource value: 0x7f060008
			public const int btnConfigCancel = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int btnConfigOk = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int btnConfigTest = 2131099655;
			
			// aapt resource value: 0x7f06001a
			public const int clearPlaylist = 2131099674;
			
			// aapt resource value: 0x7f060016
			public const int configure = 2131099670;
			
			// aapt resource value: 0x7f06001b
			public const int exit = 2131099675;
			
			// aapt resource value: 0x7f060010
			public const int imgPlayingAlbumArt = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int imgPlayingNext = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int imgPlayingPlayPause = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int imgPlayingPrev = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int imgPlayingPrevious = 2131099667;
			
			// aapt resource value: 0x7f06000c
			public const int imgPlayingShuffle = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int layoutPlaying = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int lblConfigPassword = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int lblConfigUrl = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int lblConfigUser = 2131099651;
			
			// aapt resource value: 0x7f060012
			public const int lblNowPlayingAlbum = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int lblNowPlayingArtist = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int lblNowPlayingTrack = 2131099669;
			
			// aapt resource value: 0x7f060011
			public const int lstPlaylist = 2131099665;
			
			// aapt resource value: 0x7f06000a
			public const int mainLayout = 2131099658;
			
			// aapt resource value: 0x7f060017
			public const int playlists = 2131099671;
			
			// aapt resource value: 0x7f060002
			public const int txtConfigUrl = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int txtConfigUser = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int txtPasswordConfig = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int widget55 = 2131099648;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Configuration = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NowPlaying = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int MainMenu = 2131034112;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040006
			public const int addToPlaylist = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f04000e
			public const int cancel = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int configureRequest = 2130968591;
			
			// aapt resource value: 0x7f040003
			public const int connectedToAmpache = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int connecting = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int connectingToAmpache = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int loading = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int lookupLabel = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int nowPlayingFormat = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int nowPlayingLabel = 2130968583;
			
			// aapt resource value: 0x7f04000d
			public const int ok = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int password = 2130968587;
			
			// aapt resource value: 0x7f040010
			public const int playFailureFormat = 2130968592;
			
			// aapt resource value: 0x7f040009
			public const int serverUrl = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int test = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int userName = 2130968586;
			
			private String()
			{
			}
		}
	}
}
