//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JohnMoore.AmpacheNet
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ct_default_artwork = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_icon_high_res = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_media_next = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_media_next_invert = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_media_pause = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_media_play = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_media_previous = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_media_previous_invert = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_menu_album = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_menu_artist = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_menu_clear_playlist = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_menu_help = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_menu_playlist = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_menu_search = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_menu_settings_holo_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_menu_shuffle = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_menu_shuffle_invert = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_stat_notify_musicplayer = 2130837522;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001c
			public const int albums = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int artists = 2131165211;
			
			// aapt resource value: 0x7f070009
			public const int btnConfigCancel = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int btnConfigOk = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int btnConfigTest = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int chkArtCache = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int chkSeeking = 2131165195;
			
			// aapt resource value: 0x7f07001d
			public const int clearPlaylist = 2131165213;
			
			// aapt resource value: 0x7f07001f
			public const int configure = 2131165215;
			
			// aapt resource value: 0x7f07000c
			public const int filterLayout = 2131165196;
			
			// aapt resource value: 0x7f07001e
			public const int help = 2131165214;
			
			// aapt resource value: 0x7f070011
			public const int imgPlayingAlbumArt = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int imgPlayingNext = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int imgPlayingPlayPause = 2131165202;
			
			// aapt resource value: 0x7f070017
			public const int imgPlayingPrevious = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int imgPlayingShuffle = 2131165206;
			
			// aapt resource value: 0x7f070010
			public const int layoutPlaying = 2131165200;
			
			// aapt resource value: 0x7f070005
			public const int lblConfigPassword = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int lblConfigUrl = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int lblConfigUser = 2131165187;
			
			// aapt resource value: 0x7f070015
			public const int lblNowPlayingAlbum = 2131165205;
			
			// aapt resource value: 0x7f070018
			public const int lblNowPlayingArtist = 2131165208;
			
			// aapt resource value: 0x7f070014
			public const int lblNowPlayingTrack = 2131165204;
			
			// aapt resource value: 0x7f07000f
			public const int lstPlaylist = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int mainLayout = 2131165198;
			
			// aapt resource value: 0x7f07001a
			public const int playlists = 2131165210;
			
			// aapt resource value: 0x7f070019
			public const int prgSeeking = 2131165209;
			
			// aapt resource value: 0x7f070020
			public const int search = 2131165216;
			
			// aapt resource value: 0x7f070002
			public const int txtConfigUrl = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int txtConfigUser = 2131165188;
			
			// aapt resource value: 0x7f07000d
			public const int txtFilter = 2131165197;
			
			// aapt resource value: 0x7f070006
			public const int txtPasswordConfig = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int widget55 = 2131165184;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Configuration = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Filter = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NowPlaying = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int MainMenu = 2131099648;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int addToPlaylist = 2131034118;
			
			// aapt resource value: 0x7f050011
			public const int allowSeeking = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050014
			public const int cacheArt = 2131034132;
			
			// aapt resource value: 0x7f05000e
			public const int cancel = 2131034126;
			
			// aapt resource value: 0x7f050015
			public const int configure = 2131034133;
			
			// aapt resource value: 0x7f05000f
			public const int configureRequest = 2131034127;
			
			// aapt resource value: 0x7f050003
			public const int connectedToAmpache = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int connecting = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int connectingToAmpache = 2131034114;
			
			// aapt resource value: 0x7f050012
			public const int filter = 2131034130;
			
			// aapt resource value: 0x7f050005
			public const int loading = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int lookupLabel = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int nowPlayingFormat = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int nowPlayingLabel = 2131034119;
			
			// aapt resource value: 0x7f05000d
			public const int ok = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int password = 2131034123;
			
			// aapt resource value: 0x7f050010
			public const int playFailureFormat = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int search = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int search_hint = 2131034134;
			
			// aapt resource value: 0x7f050009
			public const int serverUrl = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int test = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int userName = 2131034122;
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Search = 2130968576;
			
			private Xml()
			{
			}
		}
	}
}
